import { dedupeSmsKeywords } from "./normalize";

export const GAMBLING_KEYWORDS = {
  turkish: [
    "bahis",
    "casino",
    "slot",
    "kupon",
    "oran",
    "iddaa",
    "canli bahis",
    "sanal bahis",
    "jackpot",
    "freebet",
    "bonus",
    "hosgeldin bonusu",
    "kayip bonusu",
    "cevrimsiz bonus",
    "promosyon kodu",
    "kampanya kodu",
    "yatirim bonusu",
    "aninda para yatir",
    "hizli cekim",
    "risksiz bahis",
    "vip bahis",
    "bahis sitesi",
    "casino giris",
    "slot oyunu",
    "rulet",
    "blackjack",
    "poker",
    "parlay",
    "bet slip",
    "oran yukseltti",
    "bedava spin",
    "bedava bahis",
    "telegram bahis",
    "whatsapp bahis"
  ],
  english: [
    "bet",
    "betting",
    "casino",
    "slot",
    "poker",
    "gambling",
    "jackpot",
    "bonus",
    "free spin",
    "free spins",
    "free bet",
    "freebet",
    "deposit bonus",
    "welcome bonus",
    "sportsbook",
    "sports betting",
    "bookmaker",
    "odds boost",
    "bet slip",
    "parlay",
    "accumulator",
    "wager",
    "stake",
    "live betting",
    "casino link",
    "betting link",
    "withdraw bonus",
    "vip player",
    "high roller"
  ]
} as const;

export const SCAM_KEYWORDS = {
  turkish: [
    "hesabiniz donduruldu",
    "hesabiniz askiya alindi",
    "guvenlik uyarisi",
    "hesabiniza erisim denemesi",
    "sifrenizi guncelleyin",
    "kimlik dogrulama",
    "kartiniz kapatilacak",
    "borcunuz var",
    "acil islem yapin",
    "acil dogrulama",
    "hesap guvenligi",
    "hesabiniz hacklendi",
    "odeme bekliyor",
    "iban dogrula",
    "e devlet giris",
    "musteri temsilcisi",
    "kargo odeme",
    "teslimat ucreti",
    "ceza odemesi",
    "vergi iadesi"
  ],
  english: [
    "account suspended",
    "account frozen",
    "security alert",
    "verify your account",
    "update password",
    "identity verification",
    "card blocked",
    "debt collection",
    "urgent action required",
    "verify identity",
    "account security",
    "limited verification",
    "payment pending",
    "delivery fee",
    "customs fee",
    "tax refund",
    "bank warning",
    "fraud alert",
    "confirm payment",
    "click to verify"
  ]
} as const;

export const ADVERTISEMENT_KEYWORDS = {
  turkish: [
    "kampanya",
    "indirim",
    "firsat",
    "ozel teklif",
    "son gun",
    "stokta sinirli",
    "hemen al",
    "ucretsiz kargo",
    "sadece bugun",
    "super fiyat",
    "kupon kodu",
    "promosyon",
    "market firsati",
    "alisveris indirimi",
    "kazandiriyor"
  ],
  english: [
    "sale",
    "discount",
    "offer",
    "special deal",
    "limited time",
    "stock limited",
    "buy now",
    "free shipping",
    "today only",
    "super price",
    "coupon",
    "promo code",
    "shop now",
    "best deal",
    "exclusive offer"
  ]
} as const;

export const SAFE_TRANSACTIONAL_KEYWORDS = [
  "otp",
  "tek kullanimlik",
  "dogrulama kodu",
  "verification code",
  "2fa",
  "islem kodu",
  "security code",
  "one time password",
  "bankaniz",
  "bank",
  "hesap ozeti",
  "ekstre",
  "transaction",
  "invoice",
  "fatura",
  "randevu",
  "appointment",
  "kargo takip",
  "delivery update",
  "flight",
  "ucus"
];

export function getAllKeywords(): string[] {
  return dedupeSmsKeywords([
    ...GAMBLING_KEYWORDS.turkish,
    ...GAMBLING_KEYWORDS.english,
    ...SCAM_KEYWORDS.turkish,
    ...SCAM_KEYWORDS.english,
    ...ADVERTISEMENT_KEYWORDS.turkish,
    ...ADVERTISEMENT_KEYWORDS.english,
  ]);
}
