export const GAMBLING_KEYWORDS = {
  turkish: [
    'bahis',
    'casino',
    'slot',
    'kupon',
    'oran',
    'kazan',
    'bedava',
    'bonus',
    'poker',
    'blackjack',
    'rulet',
    'canlı bahis',
    'spor bahis',
    'iddaa',
    'toto',
    'bets10',
    'betboo',
    'nesine',
    'misli',
    'süperbahis',
    'yatırım fırsatı',
    'garanti kazanç',
    'linke tıkla',
    'hemen üye ol',
    'kampanya',
    'promosyon',
    'ücretsiz dönüş',
    'hoşgeldin bonusu',
    'ilk üyelik bonusu',
    'kayıp bonusu',
    'canlı casino',
    'casino oyunları',
    'slot makineleri',
    'jackpot',
    'büyük ödül',
    'çekiliş',
    'kazandır',
    'çevrimsiz bonus',
    'anında para yatır',
    'hızlı çekim',
    'sanal bahis',
    'yasa dışı bahis',
    'bahis sitesi',
    'deneme bonusu',
    'freeroll',
    'turnuva',
    'kampanya kodu',
    'vip',
    'cashback',
    'risksiz bahis',
    'freebet',
  ],
  english: [
    'bet',
    'betting',
    'casino',
    'slot',
    'poker',
    'gambling',
    'jackpot',
    'bonus',
    'free spin',
    'deposit',
    'withdraw',
    'odds',
    'wager',
    'stake',
    'betting site',
    'online casino',
    'live betting',
    'sportsbook',
    'sports betting',
    'bookmaker',
    'bonus code',
    'cashback',
    'freebet',
    'odds boost',
    'bet slip',
    'parlay',
    'accumulator',
    'wagering site',
  ],
};

export const SCAM_KEYWORDS = {
  turkish: [
    'hesabınız donduruldu',
    'hesabınız askıya alındı',
    'güvenlik uyarısı',
    'hesabınıza erişim denemesi',
    'şifrenizi güncelleyin',
    'kimlik doğrulama gerekli',
    'kartınız kapatılacak',
    'borcunuz var',
    'hızlı para kazan',
    'kolay para',
    'garanti gelir',
    'yatırım fırsatı',
    'dolandırıcılık uyarısı',
    'hesabınız hacklendi',
    'acil işlem yapın',
    'acil doğrulama',
    'kimlik onayı',
    'hesap güvenliği',
  ],
  english: [
    'account suspended',
    'account frozen',
    'security alert',
    'verify your account',
    'update password',
    'identity verification',
    'card blocked',
    'debt collection',
    'easy money',
    'guaranteed income',
    'investment opportunity',
    'click here',
    'urgent action required',
    'verify identity',
    'account security',
    'limited verification',
  ],
};

export const ADVERTISEMENT_KEYWORDS = {
  turkish: [
    'kampanya',
    'indirim',
    'fırsat',
    'özel teklif',
    'son gün',
    'stokta sınırlı',
    'hemen al',
    'ücretsiz kargo',
    'bedava',
    'sadece bugün',
    'süper fiyat',
    'vade farksız',
    'kupon',
    'kampanya kodu',
  ],
  english: [
    'sale',
    'discount',
    'offer',
    'special deal',
    'limited time',
    'stock limited',
    'buy now',
    'free shipping',
    'today only',
    'super price',
    'coupon',
    'promo code',
  ],
};

export function getAllKeywords(): string[] {
  return [
    ...GAMBLING_KEYWORDS.turkish,
    ...GAMBLING_KEYWORDS.english,
    ...SCAM_KEYWORDS.turkish,
    ...SCAM_KEYWORDS.english,
    ...ADVERTISEMENT_KEYWORDS.turkish,
    ...ADVERTISEMENT_KEYWORDS.english,
  ];
}
